### ISSUE TITLE
Node tests fail with boot-cljs > 2.0.0

### ISSUE THREAD

**Issue by moxaj** [crisptrutski/boot-cljs-test#77]
Currently a project of mine depends on `boot-cljs 2.0.0`. However, if I bump the version to the next stable release (`2.1.0`) or any releases beyond that, my tests fail:

```
Adding: ([doo "0.1.7"]) to :dependencies
Compiling ClojureScript...
Ľ cljs_test\generated_test_suite.js
Compile sources, elapsed time: 7254.463633 msecs

;; ======================================================================
;; Testing with Node:

module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\<...>\ams\-ueasqk\cljs_testgenerated_test_suite.out\goog\bootstrap\nodejs.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\<...>\ams\-ueasqk\cljs_test\generated_test_suite.js:18:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by crisptrutski** [comment]
From the stacktrace the error appears to be caused by a missing separator between `cljs_test` and `generated_test_suite` in a generated path. This is likely a Windows specific bug - I will look into this weekend.
